"""current schema baseline

Revision ID: 1d865fc0001
Revises:
Create Date: 2026-08-08 15:28:35.161523

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d865fc0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False, comment='批次号 BATCH-YYYYMMDD-NNN'),
    sa.Column('data_mode', sa.String(length=10), nullable=True, comment='数据模式: formal/demo'),
    sa.Column('data_version', sa.String(length=20), nullable=True, comment='数据版本'),
    sa.Column('model_version', sa.String(length=20), nullable=True, comment='模型版本'),
    sa.Column('dictionary_version', sa.String(length=20), nullable=True, comment='词典版本'),
    sa.Column('code_map_version', sa.String(length=20), nullable=True, comment='代码映射版本'),
    sa.Column('share_model_version', sa.String(length=20), nullable=True, comment='比重模型版本'),
    sa.Column('param_version', sa.String(length=50), nullable=True, comment='参数版本'),
    sa.Column('runtime_env', sa.Text(), nullable=True, comment='运行环境信息'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='上传文件SHA256哈希'),
    sa.Column('file_name', sa.String(length=300), nullable=True, comment='原始文件名'),
    sa.Column('total_rows', sa.Integer(), nullable=True, comment='数据总行数'),
    sa.Column('sport_count', sa.Integer(), nullable=True, comment='识别为体育企业的数量'),
    sa.Column('operator_name', sa.String(length=100), nullable=True, comment='操作人员'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: importing/processing/completed/locked/archived'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始处理时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=True, comment='文件名'),
    sa.Column('file_type', sa.String(length=20), nullable=True, comment='文件类型'),
    sa.Column('row_count', sa.Integer(), nullable=True, comment='数据行数'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='处理状态'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=True, comment='指标名称'),
    sa.Column('metric_value', sa.Float(), nullable=True, comment='指标值'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='指标说明'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='操作人员'),
    sa.Column('action', sa.String(length=50), nullable=True, comment='操作类型: CREATE/UPDATE/DELETE/EXPORT/REVIEW/ARBITRATE'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='操作目标类型'),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='操作目标ID'),
    sa.Column('detail', sa.Text(), nullable=True, comment='操作详情(JSON)'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('credit_code', sa.String(length=50), nullable=True, comment='统一社会信用代码'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='企业名称'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='所在区域'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='市州'),
    sa.Column('district', sa.String(length=50), nullable=True, comment='区县'),
    sa.Column('industry_code', sa.String(length=20), nullable=True, comment='行业代码'),
    sa.Column('main_business', sa.Text(), nullable=True, comment='主营业务描述'),
    sa.Column('total_revenue', sa.Float(), nullable=True, comment='总营收（万元）'),
    sa.Column('employee_count', sa.Integer(), nullable=True, comment='员工人数'),
    sa.Column('total_assets', sa.Float(), nullable=True, comment='资产总额（万元）'),
    sa.Column('registered_capital', sa.Float(), nullable=True, comment='注册资本（万元）'),
    sa.Column('scale_level', sa.String(length=20), nullable=True, comment='企业规模等级'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='经度'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('batch_id', sa.Integer(), nullable=True, comment='所属批次ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regional_scale_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True, comment='区域名称（市州/区县）'),
    sa.Column('region_type', sa.String(length=20), nullable=True, comment='区域类型: city/district'),
    sa.Column('total_enterprises', sa.Integer(), nullable=True, comment='区域内候选企业总数'),
    sa.Column('sport_enterprises', sa.Integer(), nullable=True, comment='区域内体育企业数'),
    sa.Column('estimated_scale', sa.Float(), nullable=True, comment='体育产业估算规模'),
    sa.Column('dominant_category', sa.String(length=50), nullable=True, comment='主导体育业态'),
    sa.Column('crossover_rate', sa.Float(), nullable=True, comment='跨界率'),
    sa.Column('new_candidates', sa.Integer(), nullable=True, comment='相较传统方法新增候选数'),
    sa.Column('high_risk_review_count', sa.Integer(), nullable=True, comment='高风险复核企业数(P1)'),
    sa.Column('batch_id', sa.Integer(), nullable=True, comment='批次ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise_businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('sport_category', sa.String(length=50), nullable=True, comment='体育业态分类：赛事/健身/培训/用品'),
    sa.Column('business_text', sa.Text(), nullable=True, comment='识别的体育业务描述'),
    sa.Column('is_crossover', sa.Integer(), nullable=True, comment='是否跨界经营：0=否 1=是'),
    sa.Column('sport_revenue_ratio', sa.Float(), nullable=True, comment='体育营收占比'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='识别置信度'),
    sa.Column('keywords', sa.Text(), nullable=True, comment='匹配关键词'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise_scales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True, comment='关联企业ID'),
    sa.Column('credit_code', sa.String(length=50), nullable=True, comment='统一社会信用代码'),
    sa.Column('scale_field_type', sa.String(length=30), nullable=True, comment='使用的规模字段: revenue/employee/asset/capital'),
    sa.Column('scale_field_value', sa.Float(), nullable=True, comment='规模字段原始值'),
    sa.Column('sport_scale', sa.Float(), nullable=True, comment='体育业务规模（规模字段值×SportShare）'),
    sa.Column('sport_share_used', sa.Float(), nullable=True, comment='使用的SportShare值'),
    sa.Column('measurement_type', sa.String(length=30), nullable=True, comment='测算口径: formal/proxy/relative_index'),
    sa.Column('batch_id', sa.Integer(), nullable=True, comment='批次ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('enterprise_name', sa.String(length=200), nullable=True, comment='企业名称'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='区域'),
    sa.Column('sport_category', sa.String(length=50), nullable=True, comment='业态分类'),
    sa.Column('total_revenue', sa.Float(), nullable=True, comment='总营收'),
    sa.Column('sport_revenue', sa.Float(), nullable=True, comment='测算体育产值'),
    sa.Column('sport_ratio', sa.Float(), nullable=True, comment='体育产值占比'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recognition_results_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True, comment='关联企业ID'),
    sa.Column('credit_code', sa.String(length=50), nullable=True, comment='统一社会信用代码'),
    sa.Column('sport_category', sa.String(length=50), nullable=True, comment='体育业态分类'),
    sa.Column('is_sport', sa.Integer(), nullable=True, comment='是否体育企业: 0=否 1=是'),
    sa.Column('is_crossover', sa.Integer(), nullable=True, comment='是否跨界: 0=否 1=是'),
    sa.Column('crossover_type', sa.String(length=100), nullable=True, comment='跨界类型描述'),
    sa.Column('code_type', sa.String(length=20), nullable=True, comment='行业代码类型: direct/indirect/none'),
    sa.Column('code_text_consistency', sa.String(length=30), nullable=True, comment='代码-文本一致性: consistent/partial/conflict/unknown'),
    sa.Column('sport_score', sa.Float(), nullable=True, comment='SportScore综合得分'),
    sa.Column('w1_business_scope', sa.Float(), nullable=True, comment='W1业务范围占比'),
    sa.Column('w2_keyword_density', sa.Float(), nullable=True, comment='W2关键词密度'),
    sa.Column('w3_code_weight', sa.Float(), nullable=True, comment='W3行业代码权重'),
    sa.Column('w4_category_coverage', sa.Float(), nullable=True, comment='W4业态覆盖度'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='识别置信度'),
    sa.Column('total_business_lines', sa.Integer(), nullable=True, comment='总业务线数'),
    sa.Column('sport_business_lines', sa.Integer(), nullable=True, comment='体育业务线数'),
    sa.Column('keywords', sa.Text(), nullable=True, comment='匹配关键词(JSON数组)'),
    sa.Column('sport_lines_detail', sa.Text(), nullable=True, comment='体育业务线详情(JSON)'),
    sa.Column('non_sport_lines', sa.Text(), nullable=True, comment='非体育业务线(JSON)'),
    sa.Column('model_version', sa.String(length=20), nullable=True, comment='模型版本'),
    sa.Column('batch_id', sa.Integer(), nullable=True, comment='批次ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True, comment='关联企业ID'),
    sa.Column('credit_code', sa.String(length=50), nullable=True, comment='统一社会信用代码'),
    sa.Column('priority', sa.String(length=5), nullable=True, comment='复核优先级: P1/P2/P3/P4'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: pending/assigned/reviewing/disputed/confirmed/info_insufficient/locked'),
    sa.Column('assigned_to_a', sa.String(length=100), nullable=True, comment='复核员A'),
    sa.Column('assigned_to_b', sa.String(length=100), nullable=True, comment='复核员B'),
    sa.Column('arbiter', sa.String(length=100), nullable=True, comment='仲裁员'),
    sa.Column('batch_id', sa.Integer(), nullable=True, comment='批次ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_share_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True, comment='关联企业ID'),
    sa.Column('credit_code', sa.String(length=50), nullable=True, comment='统一社会信用代码'),
    sa.Column('model_share', sa.Float(), nullable=True, comment='模型预测比重(0-1)'),
    sa.Column('share_band', sa.String(length=20), nullable=True, comment='比重档位: very_low/low/medium/medium_high/high'),
    sa.Column('lower_bound', sa.Float(), nullable=True, comment='预测区间下限'),
    sa.Column('upper_bound', sa.Float(), nullable=True, comment='预测区间上限'),
    sa.Column('model_confidence', sa.Float(), nullable=True, comment='模型置信度(0-1)'),
    sa.Column('main_factors', sa.Text(), nullable=True, comment='主要影响因素(JSON数组)'),
    sa.Column('manual_share', sa.Float(), nullable=True, comment='人工核定比重'),
    sa.Column('is_manual_adjusted', sa.Integer(), nullable=True, comment='是否经过人工校准: 0=否 1=是'),
    sa.Column('adjusted_by', sa.String(length=100), nullable=True, comment='校准人员'),
    sa.Column('adjusted_reason', sa.Text(), nullable=True, comment='校准理由'),
    sa.Column('share_model_version', sa.String(length=20), nullable=True, comment='比重模型版本'),
    sa.Column('batch_id', sa.Integer(), nullable=True, comment='批次ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arbitration_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_task_id', sa.Integer(), nullable=True, comment='关联复核任务ID'),
    sa.Column('arbiter_name', sa.String(length=100), nullable=True, comment='仲裁员'),
    sa.Column('reviewer_a_opinion', sa.Text(), nullable=True, comment='复核员A意见摘要'),
    sa.Column('reviewer_b_opinion', sa.Text(), nullable=True, comment='复核员B意见摘要'),
    sa.Column('final_sport_attribute', sa.String(length=20), nullable=True, comment='最终体育属性判定'),
    sa.Column('final_sport_category', sa.String(length=50), nullable=True, comment='最终体育业态'),
    sa.Column('final_sport_share', sa.Float(), nullable=True, comment='最终SportShare值'),
    sa.Column('decision_reason', sa.Text(), nullable=True, comment='裁决理由'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_task_id'], ['review_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_task_id', sa.Integer(), nullable=True, comment='关联复核任务ID'),
    sa.Column('reviewer_name', sa.String(length=100), nullable=True, comment='复核人员'),
    sa.Column('reviewer_role', sa.String(length=10), nullable=True, comment='角色: A/B'),
    sa.Column('sport_attribute', sa.String(length=20), nullable=True, comment='体育属性判定: yes/no/uncertain'),
    sa.Column('sport_category_override', sa.String(length=50), nullable=True, comment='修正后的体育业态'),
    sa.Column('sport_share_override', sa.Float(), nullable=True, comment='修正后的SportShare值'),
    sa.Column('reason', sa.Text(), nullable=True, comment='判断理由'),
    sa.Column('evidence_attachment', sa.Text(), nullable=True, comment='证据附件路径'),
    sa.Column('need_further_investigation', sa.Integer(), nullable=True, comment='是否需要补充调查: 0=否 1=是'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_task_id'], ['review_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_records')
    op.drop_table('arbitration_records')
    op.drop_table('sport_share_results')
    op.drop_table('review_tasks')
    op.drop_table('recognition_results_v2')
    op.drop_table('measurements')
    op.drop_table('enterprise_scales')
    op.drop_table('enterprise_businesses')
    op.drop_table('regional_scale_results')
    op.drop_table('enterprises')
    op.drop_table('operation_logs')
    op.drop_table('model_metrics')
    op.drop_table('data_sources')
    op.drop_table('batches')
    # ### end Alembic commands ###
